LUNES:
  - Prolongación Ciro Caldera
  - El Zavilar
  - Calle Urdaneta
  - Calle Municipal
  - Calle Guzmán
  - Calle La Paz
  - Calle Bolivar
MARTES:
  - Sector Alta Vista
  - Pache Vargas
  - Callejón Curazao
  - Calle Bella Vista
  - Sector El Cerro
  - Calle Industria
  - Calle Unión
MIÉRCOLES:
  - San Pedro
  - Santa Elena
  - Sector Las Varelas
  - Sector El Cristal
  - Lomas De La Florida
  - Calle Democracia
  - Playa Blanca
  - Tino Rodríguez
  - Urb José Leonardo
  - Delicias I Y II
  - La Cañada
JUEVES:
  - La Cienega
  - Calle La Paz Arriba
  - Calle Bolivar
  - Urb. Jorge Hernández
  - Avenida
  - Tucupido
  - Inavi
  - Cumbres De Alta Vista
  - La Perla Callejón Alta Vista
  - El Cangrejal
  - Urb. Juan Donquis
  - Cumbre I Calle Juan Rafael Ocando
VIERNES:
  - Calle Zamora
  - Calle Concepción
  - Callejón El Calvario
  - Calle Futuro
  - Calle Democracia
  - Calle Florida
  - Barrialito
  - Cayude
  - Quebrada De Hutten
  - San Ignacio
